#!/bin/bash -e

# see https://forum.snapcraft.io/t/cross-post-chromium-mir-kiosk-in-portrait-mode-rotated-mir-kiosk-layout/8175/11
mkdir -p -m 700 "$XDG_RUNTIME_DIR"
ln -sf /run/user/0/wayland-0 "$XDG_RUNTIME_DIR"/

url="$(snapctl get url)"
devmode="$(snapctl get devmode)"

# Toggle remote debugging
if [[ $devmode == true ]]; then
  export WEBKIT_INSPECTOR_SERVER=0.0.0.0:8080
fi

"$SNAP"/usr/bin/cog -P fdo "$url"